/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Boat: typeof import('./src/components/Boat.vue')['default']
    BoatStart: typeof import('./src/components/BoatStart.vue')['default']
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    copy: typeof import('./src/components/Inventory copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Inventory: typeof import('./src/components/Inventory.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Overview: typeof import('./src/components/Overview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedBoat: typeof import('./src/components/SelectedBoat.vue')['default']
    Todo: typeof import('./src/components/Todo.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
}
